# Generated by Django 5.1.3 on 2024-11-21 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("creationDate", models.DateField(auto_now_add=True)),
                ("website", models.URLField()),
            ],
            options={
                "db_table": "banks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "cin",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("familyName", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("photo", models.ImageField(upload_to="client_images/")),
                ("client_documents", models.FileField(upload_to="client_documents/")),
            ],
            options={
                "db_table": "clients",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "rib",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("balance", models.DecimalField(decimal_places=3, max_digits=15)),
                ("creation_date", models.DateField(auto_now_add=True)),
                (
                    "accountType",
                    models.CharField(
                        choices=[
                            ("current", "current"),
                            ("saving", "saving"),
                            ("fixed", "fixed"),
                            ("loan", "loan"),
                        ],
                        default="current",
                        max_length=20,
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_app.bank",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account_app.client",
                    ),
                ),
            ],
            options={
                "db_table": "accounts",
            },
        ),
    ]
