# Generated by Django 5.1.3 on 2024-12-01 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_remove_client_client_documents_remove_client_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='client',
            name='cin',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='The CIN must have 8 digits.', regex='^\\d{8}$')]),
        ),
    ]
