# Generated by Django 5.1.3 on 2024-12-01 10:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_remove_client_phonenumber_alter_client_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
