name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1.4.0
        with:
          postgresql version: 14
          postgresql db: ${{ secrets.DB_NAME }}
          postgresql user: ${{ secrets.DB_USER }}
          postgresql password: ${{ secrets.DB_PASSWORD }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest --disable-warnings
        env:
          DJANGO_SETTINGS_MODULE: bank_rest_api.settings
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost  

      - name: Deploy application
        if: success()
        run: echo "Placeholder for deployment"
