name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13  
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.DB_USER }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply migrations
        env:
          DJANGO_SETTINGS_MODULE: bank_rest_api.settings
          DATABASE_URL: "postgres://$DB_USER:$DB_PASSWORD@localhost:5432/$DB_NAME"
        run: |
          python manage.py migrate  # Create tables in the test database

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: bank_rest_api.settings
          DATABASE_URL: "postgres://$DB_USER:$DB_PASSWORD@localhost:5432/$DB_NAME"
        run: |
          python -m pytest --disable-warnings

      - name: Deploy application
        if: success()
        run: |
          echo "Placeholder for deployment"
