name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Install dependencies specified in the requirements file.

      - name: Run tests
        run: |
          export DJANGO_SETTINGS_MODULE=bank_rest_api.settings  # Ensure this points to your settings module without the `.py` extension
          python -m pytest --disable-warnings
        env:
          DJANGO_SETTINGS_MODULE: bank_rest_api.settings  


      # Placeholder for deployment
      - name: Deploy application
        if: success() 
        run: |
          echo "Placeholder for deployment"
